<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0-SNAPSHOT
 */

namespace winwin\jobQueue\integration;

use wenbinye\tars\protocol\annotation\TarsClient;
use wenbinye\tars\protocol\annotation\TarsParameter;
use wenbinye\tars\protocol\annotation\TarsReturnType;

/**
 * @TarsClient(name="JobQueueObj")
 */
interface JobQueueServant
{
    /**
     * @TarsParameter(name = "job", type = "Job")
     * @TarsReturnType(type = "int")
     *
     * @param \winwin\jobQueue\integration\Job $job
     *
     * @return int
     */
    public function put($job);

    /**
     * @TarsParameter(name = "keepDays", type = "int")
     * @TarsReturnType(type = "void")
     *
     * @param int $keepDays
     *
     * @return void
     */
    public function purge($keepDays);
}
