<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0-SNAPSHOT
 */

namespace winwin\jobQueue\servant;

use wenbinye\tars\protocol\annotation\TarsParameter;
use wenbinye\tars\protocol\annotation\TarsReturnType;
use wenbinye\tars\protocol\annotation\TarsServant;

/**
 * @TarsServant(name="JobStatObj")
 */
interface JobStatServant
{
    /**
     * @TarsReturnType(type = "JobStat")
     *
     * @return \winwin\jobQueue\servant\JobStat
     */
    public function stat();

    /**
     * @TarsParameter(name = "workerId", type = "int")
     * @TarsReturnType(type = "JobStat")
     *
     * @param int $workerId
     *
     * @return \winwin\jobQueue\servant\JobStat
     */
    public function statWorker($workerId);
}
